### ISSUE TITLE
i made a cli version in python

### ISSUE THREAD

**Issue by ItsZer0here** [tawan475/win95Key#1]
want me to share it with u?

**Comment by tawan475** [comment]
I don't think there is a need for that, but if you make a PR adding a python version of this feel free to do so!
(Plus you can use `000-0000007` or `00195-OEM-0000007-00000` if you really need the key.)

**Comment by ItsZer0here** [comment]
I just made it generate a random key based on the algorithms taken from a
reverse engineered setupx.dll

Em qui, 6 de abr de 2023 04:48, tawan475 ***@***.***>
escreveu:

**Comment by ItsZer0here** [comment]
also i only had to create ONE python script for it and i dont have a repo because why would i if its just one file
